name: Project Management

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
  issues:
    types: [opened, edited, closed, reopened]
  workflow_dispatch:
    inputs:
      cleanup-board:
        description: 'Perform comprehensive board cleanup'
        type: boolean
        default: true
      update-priorities:
        description: 'Update priorities and statuses'
        type: boolean
        default: false

jobs:
  update-project-items:
    name: Update Project Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @octokit/graphql dotenv

      - name: Update Project Status
        run: node .claude/scripts/update-project-statuses.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: "PVT_kwHODHqkes4A4KTr"
          ORGANIZATION: "CodingButterBot"
          REPOSITORY: "turbo-modern-starter"

  cleanup-project-board:
    name: Cleanup Project Board
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.cleanup-board
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @octokit/graphql dotenv

      - name: Cleanup Project Board
        run: node .claude/scripts/cleanup-project-board.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: "PVT_kwHODHqkes4A4KTr"
          ORGANIZATION: "CodingButterBot"
          REPOSITORY: "turbo-modern-starter"

  update-project-priorities:
    name: Update Project Priorities
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.update-priorities
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @octokit/graphql dotenv

      - name: Update Project Priorities
        run: node .claude/scripts/update-project-priorities.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: "PVT_kwHODHqkes4A4KTr"
          ORGANIZATION: "CodingButterBot"
          REPOSITORY: "turbo-modern-starter"

  verify-project-statuses:
    name: Verify Project Statuses
    runs-on: ubuntu-latest
    needs: [update-project-items, cleanup-project-board]
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @octokit/graphql dotenv

      - name: Verify Project Statuses
        run: node .claude/scripts/verify-project-statuses.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: "PVT_kwHODHqkes4A4KTr"
          ORGANIZATION: "CodingButterBot"
          REPOSITORY: "turbo-modern-starter"
          
  generate-workflow-badges:
    name: Generate Workflow Badges
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Generate Badges
        run: node .claude/scripts/generate-workflow-badges.js --output README.md
        
      - name: Commit updates if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "Update workflow badges [skip ci]"
          git push